[package]
name = "roapig"
version = "0.1.0"
authors = ["TheRoniOne"]
edition = "2021"

[lib]
path = "src/lib.rs"

[[bin]]
path = "src/main.rs"
name = "roapig"

[dependencies]
nom = "7.1.3"
walkdir = "2.5.0"
